name: Build and publish

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-book:
    runs-on: ubuntu-latest

    steps:
      - name: Set up repository
        uses: actions/checkout@v6
        with:
          path: repo
          fetch-depth: 2  # Fetch the last 2 commits to compare changes

      - name: Find modified TeX files
        id: scan
        run: |
          cd repo
          {
            echo "modified_files<<EOF"
            git diff --name-only HEAD~1 briefs/*.tex bareminima/*.tex
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: Compile new documents
        if: steps.scan.outputs.modified_files != ''
        uses: xu-cheng/latex-action@v4
        with:
          working_directory: repo
          work_in_root_file_dir: true
          root_file: ${{ steps.scan.outputs.modified_files }}
          
      - name: Upload to autogen repository
        run: |
          # Clone tools repository (it has the script)
          git clone https://github.com/assumptionsofphysics/tools tools
          # Clone autogen repository
          git clone https://gcarcassi:${{ secrets.AUTOGEN_TOKEN }}@github.com/assumptionsofphysics/autogen autogen
          ls -R
          # Run the script
          python tools/problem-scraper/technicalBriefIndex.py autogen/briefs/briefs.json repo/briefs/*.tex 
          python tools/problem-scraper/bareMinimumIndex.py autogen/bareminima/bareminima.json repo/bareminima/*.tex 
          cd repo
          find . -type f -iname '*.pdf' -print0 | rsync -0a --files-from=- --remove-source-files ./ ../autogen/
          cd ../autogen
          ls -R
          git add '**/*.pdf'
          git add 'briefs/briefs.json'
          git add 'bareminima/bareminima.json'
          # Commit and push only if there were changes
          if ! git diff --cached --quiet; then
            git config user.name "gcarcassi[bot]"
            git config user.email "gabriele.carcassi@gmail.com"
            git pull
            git commit -m "Updating community articles"
            git push
          else
            echo "No changes to commit."
          fi
